[project]
name = "celery-test"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.5.3",
    "redis>=7.1.0",
    "temporalio>=1.19.0",
]
classifiers = ["Private :: Do Not Upload"]

[dependency-groups]
dev = [
    "celery-types>=0.23.0",
    "flower>=2.0.1",
    "pytest>=9.0.1",
]
